name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGN_PROJECT }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues to Community project
      uses: Hivemapper/Community
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/Hivemapper/projects/1/'

